name: Hourly cron job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: create post on sanity cron job
        run: |
          curl --location --request POST 'https://blog-nextjs-sanity-five-alpha.vercel.app/api/cron-example' \
          --header 'Authorization: Bearer ${{secrets.PRIVATE_KEY_GITHUB_ACTIONS}}'
